name       : quadrapassel
version    : 3.20.0
release    : 1
source     :
    - https://mirror.umd.edu/gnome/sources/quadrapassel/3.20/quadrapassel-3.20.0.tar.xz : e6fdd182b15aaef5af06604eb48ad883ac19977f2fcf6ebb43b41d9ed13f1eb0
license    : GPL-2.0
component  : games.arcade
summary    : Quadrapassel, the GNOME version of Tetris
description: |
    Quadrapassel, the GNOME version of Tetris
builddeps  :
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(libcanberra)
    - pkgconfig(librsvg-2.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
