name       : quadrapassel
version    : '40.2'
release    : 15
source     :
    - https://download.gnome.org/sources/quadrapassel/40/quadrapassel-40.2.tar.xz : 0bd822414207c73123ed6a49f723da5ac8dd4df5d35edc099ffea2e1399cc00a
license    : GPL-2.0-or-later
component  : games.arcade
summary    : Quadrapassel, the GNOME version of Tetris
description: |
    Quadrapassel, the GNOME version of Tetris
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gsound)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(manette-0.2)
    - pkgconfig(yelp-xsl)
    - itstool
    - vala
    - yelp-tools
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
