name       : quadrapassel
version    : 3.32.0
release    : 5
source     :
    - https://download.gnome.org/sources/quadrapassel/3.32/quadrapassel-3.32.0.tar.xz : fe6ee9f45f262317606b1ea40259d363e45a126cc2e686526de9db794a0a11fe
license    : GPL-2.0
component  : games.arcade
summary    : Quadrapassel, the GNOME version of Tetris
description: |
    Quadrapassel, the GNOME version of Tetris
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(libcanberra)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(manette-0.2)
    - pkgconfig(yelp-xsl)
    - itstool
    - vala
    - yelp-tools
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
