name       : quadrapassel
version    : 3.22.0
release    : 3
source     :
    - http://ftp.gnome.org/pub/gnome/sources/quadrapassel/3.22/quadrapassel-3.22.0.tar.xz : 0ed44ef73c8811cbdfc3b44c8fd80eb6e2998d102d59ac324e4748f5d9dddb55
license    : GPL-2.0
component  : games.arcade
summary    : Quadrapassel, the GNOME version of Tetris
description: |
    Quadrapassel, the GNOME version of Tetris
builddeps  :
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(libcanberra)
    - pkgconfig(librsvg-2.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
