name       : quadrapassel
version    : 3.36.05
release    : 11
source     :
    - https://download.gnome.org/sources/quadrapassel/3.36/quadrapassel-3.36.05.tar.xz : 9b01b058b861a3cb9da535a9c94334ecd1d8b9894e870f33e2d7165863ed4b11
license    : GPL-2.0-or-later
component  : games.arcade
summary    : Quadrapassel, the GNOME version of Tetris
description: |
    Quadrapassel, the GNOME version of Tetris
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gsound)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(manette-0.2)
    - pkgconfig(yelp-xsl)
    - itstool
    - vala
    - yelp-tools
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
