name       : quadrapassel
version    : 3.22.0
release    : 4
source     :
    - git|https://git.gnome.org/browse/quadrapassel : 3e2cc9778d5dc24c2985d6463abaa02a370944c8
license    : GPL-2.0
component  : games.arcade
summary    : Quadrapassel, the GNOME version of Tetris
description: |
    Quadrapassel, the GNOME version of Tetris
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(libcanberra)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(manette-0.2)
    - pkgconfig(yelp-xsl)
    - itstool
    - vala
    - yelp-tools-devel
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
